# config/config.yaml
mongodb_central:
  username: "admin"
  password: "CentralPassword123!"
  host: "central.mongodb.server.com"
  port: 27018

mongodb_local:
  username: "admin"
  password: "LocalPassword456!"
  host: "localhost"
  port: 27018

api:
  central_token: ""
  email: "your_email@example.com"

paths:
  instances_list: "instances_list.txt"
  token_list: "tokens/token_list.txt"

logging:
  level: "INFO"
  file: "logs/app.log"
