# config/config.yaml
api:
  instance_token: "your_instance_api_token"
  livefeeds_token: "56TDjS3vpVrHpkLz76VjNGh71942TpfSG2v0T3mssoQ "
  email: "your_email@example.com"

paths:
  instances_list: "instances_list.txt"

logging:
  level: "INFO"
  file: "logs/app.log"
