# config/config.yaml
api:
  instance_token: "your_instance_api_token"
  livefeeds_token: "your_mastodon_api_token"
  email: "your_email@example.com"

paths:
  instances_list: "instances_list.txt"

logging:
  level: "INFO"
  file: "logs/app.log"

token:
